import { spawn } from "node:child_process";

export const RENDER_LIMITS = {
  maxDurationSeconds: 2 * 60 * 60,
  maxClips: 100,
  maxTracks: 32,
  maxSourceWidth: 16_384,
  maxSourceHeight: 16_384,
  maxSourceFps: 240,
} as const;

export interface RenderAssetSource {
  id: number;
  localPath: string;
  mimeType: string;
  duration: number;
  width: number;
  height: number;
  fps: number;
  hasAudio: boolean;
}

export interface StructuredRenderClip {
  id: number;
  assetId: number;
  trackId: number;
  trackType: "video" | "audio";
  sourceStart: number;
  duration: number;
  timelineStart: number;
  sortIndex: number;
  zIndex?: number;
  visible: boolean;
  muted: boolean;
  volume?: number;
  trackVolume?: number;
  positionX?: number;
  positionY?: number;
  scale?: number;
  cropLeft?: number;
  cropTop?: number;
  cropRight?: number;
  cropBottom?: number;
  videoFx?: string | null;
}

export interface RenderSpec {
  clips: StructuredRenderClip[];
  assets: RenderAssetSource[];
  width: number;
  height: number;
  fps?: number;
  background?: string;
  subtitleFile?: string;
}

export interface BuiltRenderCommand {
  args: string[];
  duration: number;
  videoLayerOrder: number[];
  audioClipIds: number[];
}

const effectFilter: Record<string, string> = {
  "Cinematic LUT": "eq=contrast=1.2:saturation=1.2:brightness=-0.05",
  "Vibrant HDR": "eq=contrast=1.1:saturation=1.45:brightness=0.05",
  "Film Grain": "eq=contrast=1.1:saturation=0.85",
  "Vignette Blur": "vignette=PI/5",
  "Glow Accent": "eq=brightness=0.1:saturation=1.25",
  Sharpen: "unsharp=5:5:0.8:3:3:0.4",
};

function finite(
  value: number | undefined,
  fallback: number,
  min: number,
  max: number,
  label: string
) {
  const resolved = value ?? fallback;
  if (!Number.isFinite(resolved) || resolved < min || resolved > max) {
    throw new Error(`${label} is outside the supported range.`);
  }
  return resolved;
}

function number(value: number) {
  return value.toFixed(6);
}

function escapeSubtitlePath(value: string) {
  // This value is generated by the server, never accepted from an API request.
  // Escaping is nevertheless required by FFmpeg's filtergraph parser.
  return value
    .replace(/\\/g, "/")
    .replace(/:/g, "\\:")
    .replace(/'/g, "\\'")
    .replace(/\[/g, "\\[")
    .replace(/\]/g, "\\]");
}

function validateSpec(spec: RenderSpec) {
  if (!Number.isSafeInteger(spec.width) || spec.width < 16 || spec.width > 4096)
    throw new Error("Output width is outside the supported range.");
  if (
    !Number.isSafeInteger(spec.height) ||
    spec.height < 16 ||
    spec.height > 4096
  )
    throw new Error("Output height is outside the supported range.");
  if (spec.clips.length === 0) throw new Error("Timeline has no media clips.");
  if (spec.clips.length > RENDER_LIMITS.maxClips)
    throw new Error(`Render exceeds the ${RENDER_LIMITS.maxClips}-clip limit.`);
  if (new Set(spec.clips.map(clip => clip.trackId)).size > RENDER_LIMITS.maxTracks)
    throw new Error(`Render exceeds the ${RENDER_LIMITS.maxTracks}-track limit.`);

  const assets = new Map(spec.assets.map(asset => [asset.id, asset]));
  for (const asset of spec.assets) {
    if (!asset.localPath) throw new Error("A media source path is missing.");
    if (
      !Number.isFinite(asset.duration) ||
      asset.duration <= 0 ||
      asset.duration > RENDER_LIMITS.maxDurationSeconds
    ) {
      throw new Error("A media source duration is outside the supported range.");
    }
    if (
      asset.width > RENDER_LIMITS.maxSourceWidth ||
      asset.height > RENDER_LIMITS.maxSourceHeight ||
      asset.fps > RENDER_LIMITS.maxSourceFps
    ) {
      throw new Error("A media source exceeds the decode safety limits.");
    }
  }
  for (const clip of spec.clips) {
    const asset = assets.get(clip.assetId);
    if (!asset) throw new Error("A timeline clip references unavailable media.");
    if (
      !Number.isFinite(clip.sourceStart) ||
      !Number.isFinite(clip.duration) ||
      !Number.isFinite(clip.timelineStart) ||
      clip.sourceStart < 0 ||
      clip.duration <= 0 ||
      clip.timelineStart < 0 ||
      clip.sourceStart + clip.duration > asset.duration + 0.05
    ) {
      throw new Error("A timeline clip has invalid trim or timing values.");
    }
    if (clip.videoFx && !effectFilter[clip.videoFx]) {
      throw new Error("A timeline clip uses an unsupported video effect.");
    }
    finite(clip.volume, 1, 0, 2, "Clip volume");
    finite(clip.trackVolume, 1, 0, 2, "Track volume");
    finite(clip.positionX, 0, -1, 1, "Horizontal position");
    finite(clip.positionY, 0, -1, 1, "Vertical position");
    finite(clip.scale, 1, 0.1, 4, "Clip scale");
    const cropLeft = finite(clip.cropLeft, 0, 0, 0.9, "Left crop");
    const cropRight = finite(clip.cropRight, 0, 0, 0.9, "Right crop");
    const cropTop = finite(clip.cropTop, 0, 0, 0.9, "Top crop");
    const cropBottom = finite(clip.cropBottom, 0, 0, 0.9, "Bottom crop");
    if (cropLeft + cropRight >= 0.95 || cropTop + cropBottom >= 0.95) {
      throw new Error("Clip crop removes too much of the source frame.");
    }
  }
}

export function buildFfmpegCommand(
  spec: RenderSpec,
  outputPath: string
): BuiltRenderCommand {
  validateSpec(spec);
  const fps = finite(spec.fps, 30, 1, 60, "Output frame rate");
  const visibleClips = spec.clips.filter(clip => clip.visible);
  if (visibleClips.length === 0)
    throw new Error("Timeline has no visible or audible media clips.");
  const duration = Math.max(
    ...visibleClips.map(clip => clip.timelineStart + clip.duration)
  );
  if (duration <= 0 || duration > RENDER_LIMITS.maxDurationSeconds) {
    throw new Error("Render duration is outside the supported range.");
  }

  const usedAssetIds = [
    ...new Set(visibleClips.map(clip => clip.assetId)),
  ].sort((a, b) => a - b);
  const sourceMap = new Map(spec.assets.map(asset => [asset.id, asset]));
  const inputIndex = new Map<number, number>();
  const args = ["-hide_banner", "-nostdin", "-y"];
  usedAssetIds.forEach((assetId, index) => {
    inputIndex.set(assetId, index);
    const asset = sourceMap.get(assetId)!;
    if (asset.mimeType.startsWith("image/")) {
      args.push("-loop", "1", "-framerate", number(fps));
    }
    args.push("-i", asset.localPath);
  });

  const filters: string[] = [
    `color=c=${spec.background ?? "black"}:s=${spec.width}x${spec.height}:r=${number(fps)}:d=${number(duration)},format=yuv420p[base]`,
  ];
  const videoClips = visibleClips
    .filter(clip => clip.trackType === "video")
    .sort(
      (a, b) =>
        (a.zIndex ?? a.trackId) - (b.zIndex ?? b.trackId) ||
        a.trackId - b.trackId ||
        a.sortIndex - b.sortIndex ||
        a.id - b.id
    );
  let composedVideo = "base";
  videoClips.forEach((clip, layer) => {
    const cropLeft = finite(clip.cropLeft, 0, 0, 0.9, "Left crop");
    const cropTop = finite(clip.cropTop, 0, 0, 0.9, "Top crop");
    const cropRight = finite(clip.cropRight, 0, 0, 0.9, "Right crop");
    const cropBottom = finite(clip.cropBottom, 0, 0, 0.9, "Bottom crop");
    const scale = finite(clip.scale, 1, 0.1, 4, "Clip scale");
    const positionX = finite(
      clip.positionX,
      0,
      -1,
      1,
      "Horizontal position"
    );
    const positionY = finite(
      clip.positionY,
      0,
      -1,
      1,
      "Vertical position"
    );
    const effect = clip.videoFx ? effectFilter[clip.videoFx] : undefined;
    const chain = [
      `trim=start=${number(clip.sourceStart)}:duration=${number(clip.duration)}`,
      `setpts=PTS-STARTPTS+${number(clip.timelineStart)}/TB`,
      `crop=w='max(2,trunc(iw*${number(1 - cropLeft - cropRight)}/2)*2)':h='max(2,trunc(ih*${number(1 - cropTop - cropBottom)}/2)*2)':x='iw*${number(cropLeft)}':y='ih*${number(cropTop)}'`,
      `scale=${spec.width}:${spec.height}:force_original_aspect_ratio=decrease`,
      `scale=w='max(2,trunc(iw*${number(scale)}/2)*2)':h='max(2,trunc(ih*${number(scale)}/2)*2)'`,
      "setsar=1",
      ...(effect ? [effect] : []),
      "format=yuva420p",
    ];
    filters.push(
      `[${inputIndex.get(clip.assetId)}:v:0]${chain.join(",")}[clipv${layer}]`
    );
    const next = `composed${layer}`;
    const x = `(main_w-overlay_w)/2+${number(positionX)}*main_w/2`;
    const y = `(main_h-overlay_h)/2+${number(positionY)}*main_h/2`;
    filters.push(
      `[${composedVideo}][clipv${layer}]overlay=x='max(0,min(main_w-overlay_w,${x}))':y='max(0,min(main_h-overlay_h,${y}))':eof_action=pass:shortest=0:enable='between(t,${number(clip.timelineStart)},${number(clip.timelineStart + clip.duration)})'[${next}]`
    );
    composedVideo = next;
  });

  if (spec.subtitleFile) {
    filters.push(
      `[${composedVideo}]subtitles=filename='${escapeSubtitlePath(spec.subtitleFile)}'[outv]`
    );
  } else {
    filters.push(`[${composedVideo}]null[outv]`);
  }

  const audioClips = visibleClips
    .filter(clip => {
      if (clip.muted) return false;
      const asset = sourceMap.get(clip.assetId)!;
      return clip.trackType === "audio" || asset.hasAudio;
    })
    .sort(
      (a, b) =>
        a.timelineStart - b.timelineStart ||
        a.trackId - b.trackId ||
        a.sortIndex - b.sortIndex ||
        a.id - b.id
    );
  audioClips.forEach((clip, index) => {
    const gain =
      finite(clip.volume, 1, 0, 2, "Clip volume") *
      finite(clip.trackVolume, 1, 0, 2, "Track volume");
    const delayMs = Math.round(clip.timelineStart * 1000);
    filters.push(
      `[${inputIndex.get(clip.assetId)}:a:0]atrim=start=${number(clip.sourceStart)}:duration=${number(clip.duration)},asetpts=PTS-STARTPTS,volume=${number(gain)},adelay=${delayMs}|${delayMs},aformat=sample_rates=48000:channel_layouts=stereo,apad,atrim=0:${number(duration)}[clipa${index}]`
    );
  });
  if (audioClips.length === 0) {
    filters.push(
      `anullsrc=r=48000:cl=stereo:d=${number(duration)}[outa]`
    );
  } else if (audioClips.length === 1) {
    filters.push(`[clipa0]alimiter=limit=0.95,atrim=0:${number(duration)}[outa]`);
  } else {
    filters.push(
      `${audioClips.map((_, index) => `[clipa${index}]`).join("")}amix=inputs=${audioClips.length}:duration=longest:normalize=0,alimiter=limit=0.95:attack=5:release=50,atrim=0:${number(duration)}[outa]`
    );
  }

  args.push(
    "-filter_complex",
    filters.join(";"),
    "-map",
    "[outv]",
    "-map",
    "[outa]",
    "-t",
    number(duration),
    "-r",
    number(fps),
    "-c:v",
    "libx264",
    "-preset",
    "medium",
    "-crf",
    "20",
    "-pix_fmt",
    "yuv420p",
    "-c:a",
    "aac",
    "-b:a",
    "192k",
    "-movflags",
    "+faststart",
    "-progress",
    "pipe:2",
    "-nostats",
    outputPath
  );
  return {
    args,
    duration,
    videoLayerOrder: videoClips.map(clip => clip.id),
    audioClipIds: audioClips.map(clip => clip.id),
  };
}

export interface RunFfmpegOptions {
  signal: AbortSignal;
  duration: number;
  timeoutMs?: number;
  onProgress?: (progress: number) => void;
  shouldCancel?: () => Promise<boolean>;
  onHeartbeat?: () => Promise<boolean>;
}

export async function runFfmpegProcess(
  args: string[],
  options: RunFfmpegOptions
) {
  const binary = process.env.FFMPEG_PATH || "ffmpeg";
  await new Promise<void>((resolve, reject) => {
    const child = spawn(binary, args, {
      windowsHide: true,
      stdio: ["ignore", "ignore", "pipe"],
    });
    let settled = false;
    let lastProgress = 0;
    let pollBusy = false;
    const finish = (error?: Error) => {
      if (settled) return;
      settled = true;
      clearTimeout(timeout);
      clearInterval(poll);
      options.signal.removeEventListener("abort", abort);
      error ? reject(error) : resolve();
    };
    const abort = () => {
      child.kill("SIGKILL");
      finish(new Error("Render cancelled."));
    };
    const timeout = setTimeout(() => {
      child.kill("SIGKILL");
      finish(new Error("Render exceeded the processing time limit."));
    }, options.timeoutMs ?? 15 * 60 * 1000);
    const poll = setInterval(() => {
      if (pollBusy || settled) return;
      pollBusy = true;
      void Promise.all([
        options.shouldCancel?.() ?? false,
        options.onHeartbeat?.() ?? true,
      ])
        .then(([cancelled, leaseAlive]) => {
          if (cancelled || !leaseAlive) abort();
        })
        .catch(() => abort())
        .finally(() => {
          pollBusy = false;
        });
    }, 500);
    options.signal.addEventListener("abort", abort, { once: true });
    child.once("error", () =>
      finish(new Error("FFmpeg is not installed or could not be started."))
    );
    child.stderr.on("data", (chunk: Buffer) => {
      const text = chunk.toString("utf8");
      for (const match of text.matchAll(/out_time_ms=(\d+)/g)) {
        const progress = Math.min(
          95,
          Math.floor((Number(match[1]) / 1_000_000 / options.duration) * 95)
        );
        if (progress >= lastProgress + 2) {
          lastProgress = progress;
          options.onProgress?.(progress);
        }
      }
    });
    child.once("close", code => {
      if (settled) return;
      if (code === 0) finish();
      else finish(new Error(`FFmpeg rejected or could not decode the media (exit ${code ?? "unknown"}).`));
    });
  });
}

export async function renderTimelineToFile(
  spec: RenderSpec,
  outputPath: string,
  options: Omit<RunFfmpegOptions, "duration">
) {
  const command = buildFfmpegCommand(spec, outputPath);
  await runFfmpegProcess(command.args, {
    ...options,
    duration: command.duration,
  });
  return command;
}
